export const apiKey = "69bba2f5467e7c956ecaaa7af1cc21a6";
export const apiRAT = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2OWJiYTJmNTQ2N2U3Yzk1NmVjYWFhN2FmMWNjMjFhNiIsInN1YiI6IjY2MzUyN2U0OTlkNWMzMDEyNjU3NzhiMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ._QXgq2rIB6fX_fni3NVUlSbASV-S6jFomm42-d2T52c";
export const appTitle = "ScreenScape";
export const endPointSearch = "https://api.themoviedb.org/3/movie/";
export const endPointPlayingNow = "https://api.themoviedb.org/3/movie/now_playing";
export const endPointPopular = "https://api.themoviedb.org/3/movie/popular";
export const endPointTopRated = "https://api.themoviedb.org/3/movie/top_rated";
export const endPointUpcoming = "https://api.themoviedb.org/3/movie/upcoming";
export const imageBaseURL = "https://image.tmdb.org/t/p/"
export const endPointMovieCredits = "https://api.themoviedb.org/3/movie/";
export const appStorageName = 'movie-app-favs';
export const movieGenreBaseURL = "https://api.themoviedb.org/3/discover/movie";
export const movieGenreBaseURLAfterAPI = "&with_genres=";
export const listOfGenres = "https://api.themoviedb.org/3/genre/movie/list";
